routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::resource('basic_settings','BasicSettingController');
	Route::resource('incomes','IncomeHeadController');
	Route::resource('ships','ShipController');
	Route::resource('ship_expenses','ShipExpenseController');
	Route::resource('ship_expense_heads','ShipExpenseHeadController');
	Route::resource('trips','TripController');
	Route::resource('collections','CollectionController');
	Route::resource('expense_heads','ExpenseHeadController');
	Route::resource('expenses','ExpenseController');
	Route::resource('managers','ManagerController');
	Route::resource('cargos','CargoController');
	Route::resource('agencies', 'AgencyController');
	Route::resource('products', 'ProductController');
	Route::resource('customers', 'CustomerController');
	Route::resource('cargo_expense_heads', 'CargoExpenseHeadController');
	Route::resource('cargo_trips', 'CargoTripController');
	Route::resource('cargo_expenses', 'CargoExpenseController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('demurrages', 'DemurrageController');
	Route::resource('get_demurrages', 'GetDemurrageController');
	Route::resource('payments', 'PaymentController');

	/*
	* Hotel Reservation Routes
	*/
	
	Route::resource('hotel_expense_heads', 'HotelExpenseHeadController');
	Route::resource('hotel_informations', 'HotelInformationController');
	Route::resource('hotel_expenses', 'HotelExpenseController');

	/*
	 * Employee management system  
	 */
	Route::resource('employees', 'EmployeeController');

});

app/Models/CargoExpense.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CargoExpense extends Model
{
    protected $fillable = [
        'cargo_trip_id', 'head_id', 'amount', 'status'
    ];

    public function cargo_trip()
    {
        return $this->belongsTo('App\Models\CargoTrip', 'cargo_trip_id', 'id');
    }

    public function expenseHead() 

    {
        return $this->belongsTo('App\Models\CargoExpenseHead', 'head_id', 'id');
    }


}

app/Http/Controllers/CargoExpenseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\CargoTrip;
use App\Models\CargoExpense;
use App\Models\CargoExpenseHead;
use App\Models\Cargo;

class CargoExpenseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['cargo_trips'] = CargoTrip::where('is_expense',1)->get();
        // $data['cargo_expenses'] = CargoExpense::all();
        return view('cargo_expense/index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$data['cargos'] = Cargo::all();
        $data['cargo_expense_heads'] = CargoExpenseHead :: all();
        $data['cargo_trips'] = CargoTrip::all();
        $data['cargo_trip_id'] = @$_GET['id'];
        return view('cargo_expense/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //  dd($request->all());
        //  return; 
        $post_data = $request->input();
        $total_expence = 0;
        foreach($post_data['head_id'] as $key=>$value){
            $data = array(
                'cargo_trip_id' =>$post_data['cargo_trip_id'],
                'head_id' => $value,
                'amount'=>$post_data['amount'][$key], 
                'status'=>1
            );
            // dd($data);
            // return;
            CargoExpense::create($data);
            $total_expence +=$post_data['amount'][$key];
            
        }
        CargoTrip::where('id',$post_data['cargo_trip_id'])->update(array('is_expense' =>1,'total_expense'=>$total_expence));
        return redirect()->route('cargo_expenses.index')->withStatus(__('Cargo Expense data  successfully created.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $data['cargo_trips'] =  CargoTrip::where('status', 1)->get();
        $data['cargo_expense_heads'] =  CargoExpenseHead::where('status',1)->get();
        $data['cargo_expenses'] = CargoExpense::where('cargo_trip_id',$id)->get();
        $data['cargo_trip_id'] = $id; 
       
        return view('cargo_expense.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        CargoExpense::where('cargo_trip_id', $request->input('cargo_trip_id'))->delete(); 
        $post_data = $request->input();
        $total_expence = 0;
        foreach($post_data['head_id'] as $key=>$value){
            $data = array(
                'cargo_trip_id' =>$post_data['cargo_trip_id'],
                'head_id' => $value,
                'amount'=>$post_data['amount'][$key], 
                'status'=>1
            );
            // dd($data);
            // return;
            CargoExpense::create($data);
            $total_expence +=$post_data['amount'][$key];
            
        }
        CargoTrip::where('id',$post_data['cargo_trip_id'])->update(array('is_expense' =>1,'total_expense'=>$total_expence));
        return redirect()->route('cargo_expenses.index')->withStatus(__('Update expenses data successfully.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        CargoExpense::where('cargo_trip_id', $id)->delete();
         return redirect()->route('cargo_expenses.index')->withStatus(__('Expenses data deleted successfully.'));
    }
}

resources/views/cargo_expense/create.blade.php
@extends('layouts.app', ['title' => __('Create Cargo/Coaster Expense')])

@section('content')
    @include('users.partials.header', ['title' => __('Create Cargo/Coaster Expense')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Cargo/Coaster Expenses Create') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('cargo_expenses.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('cargo_expenses.store') }}" autocomplete="off">
                            @csrf
                            
                            
                            <div class="pl-lg-4">
                            <div class="form-row">
                                
                            <div class="form-group col-md-12">
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Cargo/Coaster Trip</label>
                                    <select class="form-control" name="cargo_trip_id" id="cargo_trip_id" required="">
                                        <option value="">---Select Trip---</option>>
                                        @foreach($cargo_trips as $cargo_trip)
                                            <option value="{{ $cargo_trip->id }}"
                                                {{ $cargo_trip->id==$cargo_trip_id ? 'selected' : '' }}>
                                              Trip id: {{ $cargo_trip->trip_auto_id }} Destination Form : {{ $cargo_trip->des_form }}  | Destination To : {{ $cargo_trip->des_to }}|{{ $cargo_trip->cargo_id }}| | Start Date : {{ date('d:m:Y', strtotime($cargo_trip->selling_date)) }} | End Date : {{ date('d:m:Y', strtotime($cargo_trip->unload_date)) }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>

                            </div>
                            <div class="col-md-12">
                                <div class="form-row">
                                    <div class="row col-md-10" id="expense_mult">
                                        
                                            <!-- js form add -->
                                            <div class="form-group col-md-5">
                                                <label class="form-control-label" for="head_id">{{ __('Cargo Expense Head') }}</label>
                                                <select class="form-control" name="head_id[]" id="head_id" required="">
                                                    <option value="">---select cargo trip expense head ---</option>>
                                                    @foreach($cargo_expense_heads as $cargo_expense_head)
                                                        <option value="{{ $cargo_expense_head->id }}">{{ $cargo_expense_head->name }}</option>
                                                    @endforeach
                                                </select>
                                                
                                            </div>

                                            <div class="form-group col-md-5">
                                                <label class="form-control-label" for="amount">{{ __('Amount') }}</label>
                                                <input type="number" name="amount[]" id="amount" class="form-control form-control-alternative" placeholder="{{ __('Enter amount') }}" value="" required="">
                                                
                                            </div>
                                            <!-- js from end -->
                                        
                                    </div>

                                    <div id="new_head" class="row col-md-10" style="display:none"> 
                                       
                                    </div>

                                    <div class="col-md-1 ">
                                        <p class="pt-3"></p>
                                        <span  id="add" class="btn btn-primary px-5" style="width:100%;"><i class="fas fa-plus"></i></span>
                                    </div>
                               
                            </div>
                           
                            
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

@section('script')
<script type="text/javascript">
$(document).ready(function(){
  $(document).on('click', '#add',function(){
      $('#new_head').append(($('#expense_mult').html()));
      $('#new_head').append($('<div class="cross col-md-1 mt-5"><i class="fas fa-times btn btn-sm btn-warning"></i></div>'));
      $('#new_head').css('display',''); 
  })
  $(document).on('click', '.cross', function(){
    $(this).prev().remove();
    $(this).prev().remove();
    $(this).remove();
  }) 
});
</script>
@endsection

resources/views/cargo_expense/edit.blade.php
@extends('layouts.app', ['title' => __('Update  Cargo Trip Expense')])

@section('content')
    @include('users.partials.header', ['title' => __('Cargo Trip Expense')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Cargo Trip Expenses Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('cargo_expenses.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('cargo_expenses.update', array('id', $cargo_trip_id)) }}" autocomplete="off">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="pl-lg-4">
                            <div class="form-row">
                                
                            <div class="form-group col-md-12">
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Trip select</label>
                                    <select class="form-control" name="cargo_trip_id" id="cargo_trip_id">
                                    
                                        @foreach($cargo_trips as $cargo_trip)
                                            <option value="{{ $cargo_trip->id }}" >{{ $cargo_trip->cargo_id }} | Start Date : {{ date('d:m:Y', strtotime($cargo_trip->selling_date)) }} | End Date : {{ date('d:m:Y', strtotime($cargo_trip->unload_date)) }}</option>
                                        @endforeach
                                    </select>
                                </div>

                            </div>
                            <div class="col-md-12">
                                <div class="form-row">
                                    @foreach($cargo_expenses as $cargo_expense)
                                     <div class="row col-md-10" id="">
                                        
                                            <!-- js form add -->
                                            <div class="form-group col-md-5">
                                                <label class="form-control-label" for="head_id">{{ __('Cargo Expense Head') }}</label>
                                                <select class="form-control" name="head_id[]" id="head_id" required="">
                                                    @foreach($cargo_expense_heads as $cargo_expense_head)
                                                        <option value="{{ $cargo_expense_head->id }}" {{ @$expense->head_id == @$cargo_expense_head->id ? 'selected="selected"' : '' }}>{{ $cargo_expense_head->name }}</option>
                                                    @endforeach
                                                </select>
                                                
                                            </div>

                                            <div class="form-group col-md-5">
                                                <label class="form-control-label" for="amount">{{ __('Amount') }}</label>
                                                <input type="number" name="amount[]" id="amount" class="form-control form-control-alternative{{ $errors->has('amount') ? ' is-invalid' : '' }}" placeholder="{{ __('Amount') }}" value="{{ $cargo_expense->amount }}" required="">
                                               
                                        
                                            </div>
                                            <!-- js from end -->
                                        
                                    </div>
                                    @endforeach
                                    <div class="row col-md-10" id="expense_mult">
                                        
                                            <!-- js form add -->
                                            <div class="form-group col-md-5">
                                                <label class="form-control-label" for="head_id">{{ __('Cargo Expense Head') }}</label>
                                                <select class="form-control" name="head_id[]" id="head_id" required="">
                                                    <option value="">---select expense head---</option>>
                                                    @foreach($cargo_expense_heads as $cargo_expense_head)
                                                        <option value="{{ $cargo_expense_head->id }}">{{ $cargo_expense_head->name }}</option>
                                                    @endforeach
                                                </select>
                                                
                                            </div>

                                            <div class="form-group col-md-5">
                                                <label class="form-control-label" for="amount">{{ __('Amount') }}</label>
                                                <input type="number" name="amount[]" id="amount" class="form-control form-control-alternative{{ $errors->has('amount') ? ' is-invalid' : '' }}" placeholder="{{ __('Amount') }}" value="" required="">
                                                
                                                @if ($errors->has('amount'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('amount') }}</strong>
                                                    </span>
                                                @endif
                                        
                                            </div>
                                           <div class="cross col-md-1 mt-5"><i class="fas fa-times btn btn-sm btn-warning"></i></div>
                                        
                                    </div>

                                    <div id="new_head" class="row col-md-10" style="display:none"> 
                                       
                                    </div>

                                    <div class="col-md-1 ">
                                        <p class="pt-3"></p>
                                        <span  id="add" class="btn btn-primary px-5" style="width:100%;"><i class="fas fa-plus"></i></span>
                                    </div>
                               
                            </div>
                           
                            
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

@section('script')
<script type="text/javascript">
$(document).ready(function(){
  $(document).on('click', '#add',function(){
      $('#new_head').append(($('#expense_mult').html()));
      $('#new_head').append($('<div class="cross col-md-1 mt-5"><i class="fas fa-times btn btn-sm btn-warning"></i></div>'));
      $('#new_head').css('display',''); 
  })
  $(document).on('click', '.cross', function(){
    $(this).prev().remove();
    $(this).prev().remove();
    $(this).remove();
  }) 
});
</script>
@endsection

resources/views/cargo_expense/index.blade.php
@extends('layouts.app', ['title' => __('Cargo/coaster Expense Management')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Cargo/coaster Expense') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('cargo_expenses.create') }}" class="btn btn-sm btn-primary">{{ __('Add Cargo/coaster Expense') }}</a>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="input-group input-group-alternative my-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-zoom-split-in  text-info"></i></span>
                                    </div>
                                    <input class="form-control form-control-alternative" placeholder="Enter TriCargop name or id" type="text"><button class="btn btn-primary">Search</button>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="col-4"></div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <!-- Collapse -->
                        <div class="container">
                            <div id="accordion">
                           
                               @foreach($cargo_trips as $key=>$cargo_trip)
                                
                                 <div class="card">
                                    <div class="card-header" id="heading{{ $key }}">
                                    <h5 class="mb-0">
                                        <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ $key }}" aria-expanded="true" aria-controls="collapseOne">
                                         Cargo Trip Id:  <span class="text-success">{{ $cargo_trip->trip_auto_id }}</span> | cargo Name: <span class="text-success">{{ $cargo_trip->cargo->name }}</span><span class="px-3 text-warning">| <small> StartDate:{{ date("F j, Y, g:i a", strtotime($cargo_trip->selling_date)) }} | Enddate: {{ date("F j, Y, g:i a", strtotime($cargo_trip->unload_date)) }}</small></span>  <span class="float-right badge badge-danger">Total Expense: {{ $cargo_trip->total_expense }} BDT</span> 
                                        </button>
                                    </h5>
                                    </div>

                                    <div id="collapse{{ $key }}" class="collapse" aria-labelledby="heading{{ $key }}" data-parent="#accordion">
                                    <div class="card-body">

                                        <div class="table-responsive">
                                        <!-- Table start -->
                                        <table class="table">
                                            <thead class="thead-light">
                                                <tr>
                                                   
                                                    <th scope="col">{{ __('Particular') }}</th>
                                                    <th scope="col" class="text-right">{{ __('Amount') }}</th>
                                                    
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @php 
                                                @$grand_total = 0;
                                                @endphp
                                                @foreach(@$cargo_trip->expenses as $expense)
                                                <tr>

                                                    <td>{{ @$expense->expenseHead->name }}</td>
                                                    <td class="text-right">{{ @$expense->amount }}</td>
                                                </tr>
                                                @php 
                                                @$grand_total += $expense->amount;
                                                @endphp
                                                @endforeach
                                                <tr>
                                                    
                                                    <th class="text-primary bg-light">Grand Total</th>
                                                    <th class="text-right text-primary bg-light"> {{ @$grand_total }}</th>
                                                </tr>
                                                
                                                <tr class="text-right">
                                                    <td colspan="3">
                                                        <div class="dropdown">
                                                            <button class="btn btn-secondary dropdown-toggle bg-primary text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            Option
                                                            </button>
                                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                                <a class="dropdown-item" href="{{ route('cargo_expenses.edit', array('id' => $cargo_trip->id))}}"><i class="fas fa-edit text-info"></i>Edit</a>
                                                                 <form action="{{ route('cargo_expenses.destroy',  array('id'=>$cargo_trip->id)) }}" method="POST">
                                                                @csrf 
                                                                <input type="hidden" name="_method" value="DELETE">
                                                                <i class="fas fa-trash-alt text-danger pl-3"></i>
                                                                <button class="text-danger bg-white pl-3" onclick="return deleteFunction()" type="submit" style="border:none;">Delete</button>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                            
                                        </table>
                                            <!-- Table end -->
                                        </div>

                                    </div>
                                    </div>
                                </div>
                                
                               @endforeach
                              
                              
                                
                            </div>


                        </div>
                        <!-- Collapse end -->
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                             
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>

@endsection
@section('script')
<script>
    function deleteFunction(){
        if(!confirm("Are you sure to delete this?"))
        event.preventDefault();
    }
</script>
@endsection