routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::resource('basic_settings','BasicSettingController');
	Route::resource('incomes','IncomeHeadController');
	Route::resource('ships','ShipController');
	Route::resource('ship_expenses','ShipExpenseController');
	Route::resource('ship_expense_heads','ShipExpenseHeadController');
	Route::resource('trips','TripController');
	Route::resource('collections','CollectionController');
	Route::resource('expense_heads','ExpenseHeadController');
	Route::resource('expenses','ExpenseController');
	Route::resource('managers','ManagerController');
	Route::resource('cargos','CargoController');
	Route::resource('agencies', 'AgencyController');
	Route::resource('products', 'ProductController');
	Route::resource('customers', 'CustomerController');
	Route::resource('cargo_expense_heads', 'CargoExpenseHeadController');
	Route::resource('cargo_trips', 'CargoTripController');
	Route::resource('cargo_expenses', 'CargoExpenseController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('demurrages', 'DemurrageController');
	Route::resource('get_demurrages', 'GetDemurrageController');
	Route::resource('payments', 'PaymentController');

	/*
	* Hotel Reservation Routes
	*/
	
	Route::resource('hotel_expense_heads', 'HotelExpenseHeadController');
	Route::resource('hotel_informations', 'HotelInformationController');
	Route::resource('hotel_expenses', 'HotelExpenseController');

	/*
	 * Employee management system  
	 */
	Route::resource('employees', 'EmployeeController');

});

app/Models/Expense.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    protected $fillable = [
        'trip_id','head_id','amount','remark','status',
    ];

    public function trip()
    {
        return $this->belongsTo('App\Models\Trip', 'trip_id', 'id');
    }


    public function ship()
    {
        return $this->belongsTo('App\Models\Ship', 'ship_id', 'id');
    }



    public function expenseHead()

    {
        return $this->belongsTo('App\Models\ExpenseHead', 'head_id', 'id');
    }
    

    
}

app/Http/Controllers/ExpenseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Expense;
use App\Models\Trip;
 
use App\Models\ExpenseHead;

class ExpenseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $data['trips'] = Trip::where('is_expense',1)->orderBy('id','desc')->paginate(10);
        return view('expense/index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id = null)
    {
        $data['trips'] = Trip::where('is_expense','!=',1)->get();
        $data['expense_heads'] =  ExpenseHead::where('status',1)->get();
        $data['trip_id'] = @$_GET['id'];
        return view('expense/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//       dd($request->all());
//       return;
            $post_data = $request->input();
            $total_expence = 0;
            foreach( $post_data['head_id'] as $key=>$value){
                $data = array(
                    'trip_id'=>$post_data['trip_id'],
                    'head_id'=>$value,
                    'remark' =>$post_data['remark'][$key],
                    'amount'=>$post_data['amount'][$key], 
                    'status'=>1
                );
                Expense::create($data);
                $total_expence +=$post_data['amount'][$key];
            }
            Trip::where('id',$post_data['trip_id'])->update(array('is_expense' =>1,'total_expense'=>$total_expence));
             return redirect()->route('expenses.index', compact('expenses'))->withStatus(__('Expense data  successfully created.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['trips'] =  Trip::where('status', 1)->get();
        $data['expense_heads'] =  ExpenseHead::where('status',1)->get();
        $data['expenses'] = Expense::where('trip_id',$id)->get();
        $data['trip_id'] = $id; 
        return view('expense.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Expense::where('trip_id', $request->input('trip_id'))->delete();  
            $post_data = $request->input();
            $total_expence =0;
            foreach( $post_data['head_id'] as $key=>$value){
                $data = array(
                    'trip_id'=>$post_data['trip_id'],
                    'head_id'=>$value, 
                    'amount'=>$post_data['amount'][$key],
                    'remark'=>$post_data['remark'][$key],
                    'status'=>1
                );
                Expense::create($data);
                $total_expence +=$post_data['amount'][$key];
            }
            Trip::where('id',$post_data['trip_id'])->update(array('is_expense' =>1,'total_expense'=>$total_expence));
        return redirect()->route('expenses.index')->withStatus(__('Update expenses data successfully.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Expense::where('trip_id', $id)->delete();
         return redirect()->route('expenses.index')->withStatus(__('Expenses data deleted successfully.'));
    }
}

resources/views/expense/create.blade.php
@extends('layouts.app', ['title' => __('Create Trip Expense')])

@section('content')
    @include('users.partials.header', ['title' => __('Create Trip Expense')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Create Trip Expenses') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('expenses.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('expenses.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('Create Trip Expense information') }}</h6>
                            <div class="pl-lg-4">
                            <div class="form-row">
                                
                            <div class="form-group col-md-12">
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Trip select</label>
                                    <select class="form-control" name="trip_id" id="trip_id" required="">
                                        <option value="">---Select Trip---</option>>
                                        @foreach($trips as $trip) 
                                            <option value="{{ $trip->id }}"
                                                {{ $trip->id==$trip_id ? 'selected' : '' }}>{{ $trip->name }} | Ship: | StartDate: {{ date('d:m:Y', strtotime($trip->start_date)) }} | Enddate: {{ date('d:m:Y', strtotime($trip->end_date)) }}  </option>
                                        @endforeach
                                    </select>
                                </div>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-md-12">
                                <div class="form-row">
                                    <div class="row col-md-10" id="expense_mult">
                                        
                                            <!-- js form add -->
                                            <div class="form-group col-md-4">
                                                <label class="form-control-label" for="head_id">{{ __('Expense Head') }}</label>
                                                <select class="form-control" name="head_id[]" id="head_id" required="">
                                                    <option value="">---select trip expense head ---</option>>
                                                    @foreach($expense_heads as $expense_head)
                                                        <option value="{{ $expense_head->id }}">{{ $expense_head->name }}</option>
                                                    @endforeach
                                                </select>
                                                
                                            </div>

                                            <div class="form-group col-md-3">
                                                <label class="form-control-label" for="amount">{{ __('Amount') }}</label>
                                                <input type="number" name="amount[]" id="amount" class="form-control form-control-alternative{{ $errors->has('amount') ? ' is-invalid' : '' }}" placeholder="{{ __('Enter amount') }}" value="" required="">
                                                
                                                @if ($errors->has('amount'))
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $errors->first('amount') }}</strong>
                                                    </span>
                                                @endif
                                        
                                            </div>

                                            <!--remark--->
                                            <div class="form-group col-md-3">
                                                <label class="form-control-label" for="remark">{{ __('Remark') }}</label>
                                                <input type="text" name="remark[]" id="remark" class="form-control form-control-alternative" placeholder="{{ __('If any remark ... ') }}">

                                            </div>
                                            <!--//remark-->

                                            <!-- js from end -->
                                        
                                    </div>

                                    <div id="new_head" class="row col-md-10" style="display:none"> 
                                       
                                    </div>

                                    <div class="col-md-1 ">
                                        <p class="pt-3"></p>
                                        <span  id="add" class="btn btn-primary px-5" style="width:100%;"><i class="fas fa-plus"></i></span>
                                    </div>
                               
                            </div>
                           
                            
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

@section('script')
<script type="text/javascript">
$(document).ready(function(){
  $(document).on('click', '#add',function(){
      $('#new_head').append(($('#expense_mult').html()));
      $('#new_head').append($('<div class="cross col-md-1 mt-5"><i class="fas fa-times btn btn-sm btn-warning"></i></div>'));
      $('#new_head').css('display',''); 
  })
  $(document).on('click', '.cross', function(){
    $(this).prev().remove();
    $(this).prev().remove();
    $(this).remove();
  }) 
});
</script>
@endsection

resources/views/expense/index.blade.php
@extends('layouts.app', ['title' => __('Trip Expense Management')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Trip Expense') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('expenses.create') }}" class="btn btn-sm btn-primary">{{ __('Add Trip Expense') }}</a>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="input-group input-group-alternative my-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="ni ni-zoom-split-in  text-info"></i></span>
                                    </div>
                                    <input class="form-control form-control-alternative" placeholder="Enter Trip name or id" type="text"><button class="btn btn-primary">Search</button>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="col-4"></div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <!-- Collapse -->
                        <div class="container">
                            <div id="accordion">
                           
                               @foreach($trips as $key=>$trip)
                                 
                               @if(count($trip->expenses) > 0)

                                 <div class="card">
                                    <div class="card-header" id="heading{{ $key }}">
                                    <h5 class="mb-0">
                                        <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{ $key }}" aria-expanded="true" aria-controls="collapseOne">
                                        Trip Name: <span class="text-success">{{ $trip->name }}</span> | Ship: <span class="text-success">{{ @$trip->ship->name }}</span><span class="px-3 text-warning">| <small> StartDate:{{ date("F j, Y, g:i a", strtotime($trip->start_date)) }} | Enddate: {{ date("F j, Y, g:i a", strtotime($trip->end_date)) }}</small></span>  <span class="float-right badge badge-danger">Total Expense: {{ $trip->total_expense }} BDT</span> 
                                         </button>
                                    </h5>
                                    </div>

                                    <div id="collapse{{ $key }}" class="collapse" aria-labelledby="heading{{ $key }}" data-parent="#accordion">
                                    <div class="card-body">

                                        <div class="table-responsive">
                                        <!-- Table start -->
                                        <table class="table">
                                            <thead class="thead-light">
                                                <tr>
                                                   
                                                    <th scope="col">{{ __('Particular') }}</th>
                                                    <th scope="col">{{ __('Remark') }}</th>
                                                    <th scope="col" class="text-right">{{ __('Amount') }}</th>
                                                    
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @php 
                                                @$grand_total = 0;
                                                @endphp
                                                @foreach(@$trip->expenses as $expense)
                                                <tr>

                                                    <td>{{ @$expense->expenseHead->name}}</td>
                                                    <td>{{ $expense->remark }}</td>
                                                    <td class="text-right">{{ $expense->amount }}</td>
                                                </tr>
                                                @php 
                                                @$grand_total += $expense->amount;
                                                @endphp
                                                @endforeach
                                                <tr>
                                                    
                                                    <th class="text-primary bg-light">Grand Total</th>
                                                    <th class="text-primary bg-light"></th>
                                                    <th class="text-right text-primary bg-light"> {{ @$grand_total }}</th>
                                                </tr>
                                                
                                                <tr class="text-right">
                                                    <td colspan="3">
                                                        <div class="dropdown">
                                                            <button class="btn btn-secondary dropdown-toggle bg-primary text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            Option
                                                            </button>
                                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                                <a class="dropdown-item" href="{{ route('expenses.edit', array('id' => $trip->id))}}"><i class="fas fa-edit text-info"></i>Edit</a>
                                                                 <form action="{{ route('expenses.destroy',  array('id'=>$trip->id)) }}" method="POST">
                                                                @csrf 
                                                                <input type="hidden" name="_method" value="DELETE">
                                                                <i class="fas fa-trash-alt text-danger pl-3"></i>
                                                                <button class="text-danger bg-white pl-3" onclick="return deleteFunction()" type="submit" style="border:none;">Delete</button>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                            
                                        </table>
                                            <!-- Table end -->
                                        </div>

                                    </div>
                                    </div>
                                </div>
                                @endif
                               @endforeach
                              
                              
                                
                            </div>


                        </div>
                        
                        <!-- Collapse end -->
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                             {{ $trips->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
    
@endsection
@section('script')
<script>
    function deleteFunction(){
        if(!confirm('Are you sure to delete this?'))
        event.preventDefault();
    }
</script>
@endsection