routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::resource('basic_settings','BasicSettingController');
	Route::resource('incomes','IncomeHeadController');
	Route::resource('ships','ShipController');
	Route::resource('ship_expenses','ShipExpenseController');
	Route::resource('ship_expense_heads','ShipExpenseHeadController');
	Route::resource('trips','TripController');
	Route::resource('collections','CollectionController');
	Route::resource('expense_heads','ExpenseHeadController');
	Route::resource('expenses','ExpenseController');
	Route::resource('managers','ManagerController');
	Route::resource('cargos','CargoController');
	Route::resource('agencies', 'AgencyController');
	Route::resource('products', 'ProductController');
	Route::resource('customers', 'CustomerController');
	Route::resource('cargo_expense_heads', 'CargoExpenseHeadController');
	Route::resource('cargo_trips', 'CargoTripController');
	Route::resource('cargo_expenses', 'CargoExpenseController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('demurrages', 'DemurrageController');
	Route::resource('get_demurrages', 'GetDemurrageController');
	Route::resource('payments', 'PaymentController');

	/*
	* Hotel Reservation Routes
	*/
	
	Route::resource('hotel_expense_heads', 'HotelExpenseHeadController');
	Route::resource('hotel_informations', 'HotelInformationController');
	Route::resource('hotel_expenses', 'HotelExpenseController');

	/*
	 * Employee management system  
	 */
	Route::resource('employees', 'EmployeeController');

});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'name', 'image', 'mobile', 'address', 'nid', 'job_type', 'department', 'salary', 'remark', 'joining_date', 'status'
    ];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('employee/index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employee/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request->all();
        $request->validate([
            'name'    => 'required',
            'mobile'  => 'required',
            'address' => 'required',
            'nid'     => 'required',
            'joining_date' => 'required',
            'department'   => 'required'
        ]);

        //  $request->file('image')->getClientOriginalExtension()->move(public_path('images'));
        // // $new_name = rand() . '.' . $image->getClientOriginalExtension();
        //  //$image->move(public_path('images'), $image);

        // Employee::create($request->all());
        // back();

        // $image = $request->file('image');
        // $new_name = rand().'.'.$iamge->getClientOriginalExtension();
        // $image->move(public_path('image'), $image);
        
        $image = $request->file('image');

        $new_name = rand() . '.' . $image->getClientOriginalExtension();
        $image->move(public_path('images'), $new_name);

        $fill_data = array (
            'name'         => $request->name,
            'mobile'       => $request->mobile,
            'address'      => $request->address,
            'nid'          => $request->nid,
            'joining_date' => $request->joinig_date,
            'department'   => $request->department,
            'job_type'     => $request->job_type,
            'salary'       => $request->salary,
            'remark'       => $request->remark,
            'status'       => $request->status,
            'image'        => $new_name
        );
        Employee::create($fill_data);

        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/employee/create.blade.php
@extends('layouts.app', ['title' => __('Create Employee')])

@section('content')
    @include('users.partials.header', ['title' => __('Create Employee Information')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Create Employee') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('employees.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    @if($errors->any())
                    <div class="alert alert-danger">
                    <ul>
                    @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                    </div>
                    @endif
                    <div class="card-body">
                        <form method="post" action="{{ route('employees.store') }}" autocomplete="off">
                            @csrf
                            
                            <div class="pl-lg-4">
                            <div class="form-row">

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="iname">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative" placeholder="{{ __('Name') }}" value="" required autofocus>

                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="mobile">{{ __('Mobile Number') }}</label>
                                    <input type="text" name="mobile" id="mobile" class="form-control form-control-alternative" placeholder="{{ __('Mobile Number') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="ind">{{ __('NID') }}</label>
                                    <input type="text" name="nid" id="nid" class="form-control form-control-alternative" placeholder="{{ __('NID Number') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="image">{{ __('Photo') }}</label>
                                    <input type="file" name="image" id="image" class="form-control form-control-alternative" placeholder="{{ __('Upload photo') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-text">{{ __('Address') }}</label>
                                    <textarea rows="4" cols="50" name="address" id="address" class="form-control form-control-alternative" placeholder="{{ __('Presenrt Address') }}" required autofocus ></textarea>

                                </div>

                                <div class="form-group col-md-6">
                                    <label for="job_type">Job Type</label>
                                    <select class="form-control" name="job_type" id="job_type">
                                        <option value="">---Select JOB Type---</option>>
                                        <option value="">Full Time</option>
                                        <option value="">Part Time</option>
                                        <option value="">contractual</option>
                                       
                                    </select>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="department">{{ __('Department') }}</label>
                                    <input type="text" name="department" id="department" class="form-control form-control-alternative" placeholder="{{ __('Department') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="salary">{{ __('Salary') }}</label>
                                    <input type="text" name="salary" id="salary" class="form-control form-control-alternative" placeholder="{{ __('Salary') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="joining_date">{{ __('Joining Date') }}</label>
                                    <input type="date" name="joining_date" id="joining_date" class="form-control form-control-alternative" placeholder="{{ __('Joining Date') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="remark">{{ __('Remark') }}</label>
                                    <input type="text" name="remark" id="remark" class="form-control form-control-alternative" placeholder="{{ __('Writing text') }}" value="" required autofocus>
                                </div>

                                <div class="form-group col-md-12">
                                    <h3>Status</h3>
                                    @php
                                        if(@$product->status){
                                        $active = 'checked';
                                        $inactive = '';
                                        }else{
                                        $active = '';
                                        $inactive = 'checked';
                                    }
                                    @endphp
                                    
                                    <div class="custom-control custom-radio mb-3">
                                    <input name="status" class="custom-control-input" id="status1" type="radio" value="0" {{ $inactive }}>
                                    <label class="custom-control-label" for="status1">inactive</label>
                                    </div>
                                    <div class="custom-control custom-radio mb-3">
                                    <input name="status" class="custom-control-input" value="1" id="status2"  type="radio"  {{ $active.(!Request::segment(3)) ? 'checked' : ''}}>
                                    <label class="custom-control-label" for="status2">active</label>
                                    </div>
                                </div>
                                
                            </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app', ['title' => __('Update Manager Entry')])

@section('content')
    @include('users.partials.header', ['title' => __('Update Manager Information')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Update Manager') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('managers.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{!! action('ManagerController@update', ['id' => $manager->id]) !!}" autocomplete="off">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <h6 class="heading-small text-muted mb-4">{{ __('Update Manager information') }}</h6>
                            <div class="pl-lg-4">
                            <div class="form-row">

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="name" value="{{ $manager->name }}" class="form-control form-control-alternative" placeholder="{{ __('Name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-name">{{ __('Mobile Number') }}</label>
                                    <input type="text" name="mobile" id="mobile" value="{{ $manager->mobile }}" class="form-control form-control-alternative" placeholder="{{ __('Mobile Number') }}" required autofocus>

                                    @if ($errors->has('mobile'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('mobile') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-name">{{ __('NID') }}</label>
                                    <input type="text" name="nid" id="nid" value="{{ $manager->nid }}" class="form-control form-control-alternative" placeholder="{{ __('NID Number') }}" required autofocus>

                                    @if ($errors->has('nid'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('nid') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-name">{{ __('Photo') }}</label>
                                    <input type="file" name="photo" id="photo" value="{{ $manager->photo }}" class="form-control form-control-alternative" placeholder="{{ __('Upload photo') }}" required autofocus>

                                    @if ($errors->has('file'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('file') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-text">{{ __('Present Address') }}</label>
                                    <textarea rows="4" cols="50" name="present_address" value="{{ $manager->present_address }}" id="present_address" class="form-control form-control-alternative" placeholder="{{ __('Presenrt Address') }}" required autofocus >{{ $manager->present_address }}</textarea>

                                </div>

                                <div class="form-group col-md-6">
                                    <label class="form-control-label" for="input-text">{{ __('Permanent Address') }}</label>
                                    <textarea rows="4" cols="50" name="permanent_address" value="{{ $manager->permanent_address }}" id="permanent_address" class="form-control form-control-alternative" placeholder="{{ __('Permanetn Address') }}" required autofocus >{{ $manager->permanent_address }}</textarea>

                                </div>

                                <div class="form-group col-md-12">
                                    <h3>Status</h3>
                                    @php
                                        if(@$ship_expense_head->status){
                                            $active='checked';
                                            $inactive='';
                                        }else
                                        {
                                            $active='';
                                            $inactive='chacked';
                                        }
                                    @endphp
                                    <div class="custom-control custom-radio mb-3">
                                        <input name="status" class="custom-control-input" value="1"@php echo @$active @endphp id="radio-1" type="radio">
                                        <label class="custom-control-label" for="radio-1">Active</label>
                                    </div>
                                    <div class="custom-control custom-radio mb-3">
                                        <input name="status" class="custom-control-input" value='0' @php echo @$inactive @endphp  id="radio-2" type="radio">
                                        <label class="custom-control-label" for="radio-2">Inactive</label>
                                    </div>
                                    
                                </div>
                                
                            </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app', ['title' => __('Employee Entry')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Employee') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('managers.create') }}" class="btn btn-sm btn-primary">{{ __('Add Manager') }}</a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive p-4">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>{{ __('#SL') }}</th>
                                    <th>{{ __('Name') }}</th>
                                    <th>{{ __('Image') }}</th>
                                    <th>{{ __('Mobile') }}</th>
                                    <th>{{ __('NID') }}</th>
                                    <th>{{ __('Present Address') }}</th>
                                    <!-- <th>{{ __('Permanent Address') }}</th> -->
                                    <th>{{__('Action') }}</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                               @foreach($managers as $key=>$manager)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $manager->name }}</td>
                                    <td>{{ $manager->mobile }}</td>
                                    <td><img src="{{ asset('argon') }}/img/theme/{{ $manager->photo }}" style="height:64px; width:64px;"\> </td>
                                    <td>{{ $manager->nid }}</td>
                                    <td>{{ $manager->present_address }}</td>
                                    <!-- <td>{{ $manager->permanent_address }}</td> -->
                                    <td>
                                        <div style="display:inlineblock;">
                                            <a href="{{ route('managers.edit', array('id' => $manager->id))}}" class="btn btn-sm btn-info">Edit</a>
                                    </td>
                                    <td>       
                                            <form action="{{ route('managers.destroy',  array('id'=>$manager->id)) }}" method="POST">
                                            @csrf 
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button class="btn btn-sm btn-danger" onclick="return deleteFunction()" type="submit">Delete</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                               @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection
@section('script')
<script>
    function deleteFunction(){
        if(!confirm('Are you sure to delete this?'))
        event.preventDefault();
    }
</script>
@endsection