routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::resource('basic_settings','BasicSettingController');
	Route::resource('incomes','IncomeHeadController');
	Route::resource('ships','ShipController');
	Route::resource('ship_expenses','ShipExpenseController');
	Route::resource('ship_expense_heads','ShipExpenseHeadController');
	Route::resource('trips','TripController');
	Route::resource('collections','CollectionController');
	Route::resource('expense_heads','ExpenseHeadController');
	Route::resource('expenses','ExpenseController');
	Route::resource('managers','ManagerController');
	Route::resource('cargos','CargoController');
	Route::resource('agencies', 'AgencyController');
	Route::resource('products', 'ProductController');
	Route::resource('customers', 'CustomerController');
	Route::resource('cargo_expense_heads', 'CargoExpenseHeadController');
	Route::resource('cargo_trips', 'CargoTripController');
	Route::resource('cargo_expenses', 'CargoExpenseController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('roles', 'RoleController');
	Route::resource('demurrages', 'DemurrageController');
	Route::resource('get_demurrages', 'GetDemurrageController');
	Route::resource('payments', 'PaymentController');

	/*
	* Hotel Reservation Routes
	*/
	
	Route::resource('hotel_expense_heads', 'HotelExpenseHeadController');
	Route::resource('hotel_informations', 'HotelInformationController');
	Route::resource('hotel_expenses', 'HotelExpenseController');

	/*
	 * Employee management system  
	 */
	Route::resource('employees', 'EmployeeController');

});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name'];
    public function permissions(){
        return $this->belongsToMany('App\Models\Permission', 'role_permissions', 'role_id', 'permission_id');
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Permission;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles['roles'] = Role::all();
        return view('role.index', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions['permissions'] = Permission::all();
        return view('role.create', $permissions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $role = Role::create($request->only('name'));
        $role->permissions()->sync($request->permissions);
        return redirect()->route('roles.index')->withStatus( __('Role Successfully Insert!') ); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role['role'] = Role::findOrFail($id);
        return view('role.show', $role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['permissions'] = Permission::all();
        $data['role'] = Role::findOrFail($id);
        return view('role.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $role->update($request->only('name'));
        $role->permissions()->sync($request->permissions);
        return redirect()->route('roles.index')->withStatus( __('Role Successfully Updated!') ); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/role/create.blade.php
@extends('layouts.app', ['title' => __('Role Entry')])

@section('content')
    @include('users.partials.header', ['title' => __('Role Information')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Role') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('roles.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('Role information') }}</h6>
                            <div class="pl-lg-4">
                            <div class="form-row">

                                <div class="form-group col-md-6">
                                    <label class="form-control-name" for="name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative" placeholder="{{ __('Name') }}" required autofocus>

                                </div>
                            </div>
                            <div class="row">
                                    @foreach($permissions as $permission)
                                    <div class="col-md-4">
                                    <div class="form-group">
                                    <div class="custom-control custom-checkbox mb-3">
                                    <input class="custom-control-input" id="{{ $permission->permission_name }}" name="permissions[]" value="{{ $permission->id }}" type="checkbox">
                                    <label class="custom-control-label" for="{{ $permission->permission_name }}">{{ $permission->label }}</label>
                                    </div>
                                    </div>
                                    </div>
                                    @endforeach
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/role/edit.blade.php
@extends('layouts.app', ['title' => __('Role Entry')])

@section('content')
    @include('users.partials.header', ['title' => __('Role Information')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Role') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{!! action('RoleController@update', ['id' => $role->id]) !!}" autocomplete="off">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <h6 class="heading-small text-muted mb-4">{{ __('Role information') }}</h6>
                            <div class="pl-lg-4">
                            <div class="form-row">

                                <div class="form-group col-md-6">
                                    <label class="form-control-name" for="name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="name" class="form-control form-control-alternative" value="{{ $role->name }}" required autofocus>

                                </div>
                            </div>
                            <div class="row">
                                    @foreach($permissions as $permission)
                                    <div class="col-md-4">
                                    <div class="form-group">
                                    <div class="custom-control custom-checkbox mb-3">
                                    <input class="custom-control-input" id="{{ $permission->permission_name }}" name="permissions[]" value="{{ $permission->id }}" type="checkbox" {{ $role->permissions ? $role->permissions->contains($permission->id) ? 'checked' : '' : '' }}>
                                    <label class="custom-control-label" for="{{ $permission->permission_name }}">{{ $permission->label }}</label>
                                    </div>
                                    </div>
                                    </div>
                                    @endforeach
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.app', ['title' => __('Role Information')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Role') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('roles.create') }}" class="btn btn-sm btn-primary">{{ __('Add Role') }}</a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>{{ __('#SL') }}</th>
                                    <th>{{ __('Name') }}</th>
                                    <th></th>
                                    <th class="text-right">{{__('Action') }}</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($roles as $key=>$role)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $role->name }}</td>
                                    <td class="text-right">
                                        <a href="{{route('roles.edit', array('id'=>$role->id)) }}" class="btn btn-sm btn-info">Edit</a>
                                        <a href="{{route('roles.show', array('id'=>$role->id)) }}" class="btn btn-sm btn-success">View</a>
 
                                    </td>
                                    <td>
                                        <form action="{{ route('roles.destroy',  array('id'=>$role->id)) }}" method="POST">
                                        @csrf 
                                        <input type="hidden" name="_method" value="DELETE"> 
                                        <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                    
                                </tr>
                                @endforeach
                                   
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/role/show.blade.php
@extends('layouts.app', ['title' => __('Role Information')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Role Name : ') }}{{ $role->name }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary">{{ __('Back to List') }}</a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>{{ __('#SL') }}</th>
                                    <th>{{ __('Permission Name') }}</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($role->permissions as $key=>$permission)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $permission->label }}</td>
                                    
                                </tr>
                                @endforeach
                                   
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection